MobList = {
  Earth = {
    "Alien",
    "Android 17"
    "Android 18",
    "Android Prototype A",
    "Android Prototype B",
    "Android Prototype S",
    "Bear",
    "Big Snake",
    "Black Scorpian",
    "Brute",
    "Chi Expert",
    "Corrupt Officer",
    "Evil Crane Student",
    "Evil Majin",
    "Evil Namek",
    "Evil Saiyan",
    "Evil Saiyan [SSJ]",
    "Galactic Patrol",
    "Gorila",
    "Imperfect Cell",
    "Kick Boxer",
    "Kung Fu Master",
    "Mad Scientist",
    "Purple Fighter", 
    "Red Ribbon Gunner",
    "Saibablue",
    "Saibaman",
    "Saibared",
    "Scorpian",
    "Shielded Tank",
    "Snake",
    "Thug",
    "Universal Champion",
    "Yeti"
  }
}
